// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data.Context;

#nullable disable

namespace Restaurant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorii");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.ImaginePreparat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PathImagine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreparatId");

                    b.ToTable("ImaginiPreparat");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Preparat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CantitatePortie")
                        .HasColumnType("real");

                    b.Property<float>("CantitateTotala")
                        .HasColumnType("real");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Preparate");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.ImaginePreparat", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Preparat", "Preparat")
                        .WithMany("Imagini")
                        .HasForeignKey("PreparatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preparat");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Preparat", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Preparate")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Categorie", b =>
                {
                    b.Navigation("Preparate");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Preparat", b =>
                {
                    b.Navigation("Imagini");
                });
#pragma warning restore 612, 618
        }
    }
}
